development:
  adapter: sqlite3
  database: db/ideation_dev.sqlite.db

test:
  adapter: sqlite3
  database: db/ideation_test.sqlite.db

production:
  adapter: postgresql
  encoding: unicode
  database: ideation_production
